CREATE TABLE associado (
	id SERIAL NOT NULL,
	cpf CHARACTER(11) NOT NULL,
	nome CHARACTER VARYING NOT NULL,
	PRIMARY KEY(id),
	UNIQUE (cpf)
);

CREATE TABLE pauta (
	id SERIAL NOT NULL,
	nome CHARACTER VARYING NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE sessao (
	id SERIAL NOT NULL,
	id_pauta INTEGER NOT NULL,
	descricao CHARACTER VARYING NOT NULL,
	data_hora_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	data_hora_fechamento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(id_pauta) REFERENCES pauta (id) ON DELETE CASCADE
);

CREATE TABLE voto (
	id SERIAL NOT NULL,
	id_sessao INTEGER NOT NULL,
	id_associado INTEGER NOT NULL,
	valor BOOLEAN NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(id_sessao) REFERENCES sessao (id) ON DELETE CASCADE,
	FOREIGN KEY(id_associado) REFERENCES associado (id)
);